name: Build XRomConverter
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Publish
        run: dotnet publish XRomConverter.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: XRomConverter-Win64
          path: bin/Release/net8.0-windows/win-x64/publish/
